name: Run all tests on CPU (GitHub-hosted)

on: push

jobs:
  run_tests_torch_and_tf:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install .[sklearn,tf,torch,testing]

    - name: Run all tests on CPU
      env:
        OMP_NUM_THREADS: 1
      run: |
        python -m pytest -n 8 --dist=loadfile -s -v ./tests/

